### ISSUE TITLE
Exceptions thrown from Specflow 3.7.13+

### ISSUE THREAD

**Issue by cliveontoast** [AdCodicem/SpecFlowMicrosoftDependencyInjection#3]
Hi,

I've been using your nuget package for a year now and it has been wonderful. Thanks for putting in the effort to create it.

In my experience, from Specflow 3.7.13 onwards, this project no longer works with the error

```
  Failed AddTwoNumbers
  Error Message:
   Assembly Initialization method SpecFlowProject1_MSTestAssemblyHooks.AssemblyInitialize threw exception. System.MissingMethodException: System.MissingMethodException: Method not found: 'Void BoDi.ObjectContainer.RegisterTypeAs(System.String)'.. Aborting test execution.
  Stack Trace:
      at AdCodicem.SpecFlow.MicrosoftDependencyInjection.DependencyInjectionPlugin.<>c.<Initialize>b__3_0(Object _, CustomizeGlobalDependenciesEventArgs args)
   at TechTalk.SpecFlow.Plugins.RuntimePluginEvents.RaiseCustomizeGlobalDependencies(ObjectContainer container, SpecFlowConfiguration specFlowConfiguration)
   at TechTalk.SpecFlow.Infrastructure.ContainerBuilder.CreateGlobalContainer(Assembly testAssembly, IRuntimeConfigurationProvider configurationProvider)
   at TechTalk.SpecFlow.MSTest.SpecFlowPlugin.MsTestContainerBuilder.CreateGlobalContainer(Assembly testAssembly, IRuntimeConfigurationProvider configurationProvider)
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunnerManager(Assembly testAssembly, IContainerBuilder containerBuilder)
   at TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerManager(Assembly testAssembly, IContainerBuilder containerBuilder, Boolean createIfMissing)
   at TechTalk.SpecFlow.TestRunnerManager.OnTestRunStart(Assembly testAssembly, IContainerBuilder containerBuilder)
   at SpecFlowProject1_MSTestAssemblyHooks.AssemblyInitialize(TestContext testContext) in ....\SpecFlowProject1\obj\Debug\netcoreapp3.1\MSTest.AssemblyHooks.cs:line 22
   ```

I've created the example in [this commit](https://github.com/cliveontoast/AdCodicem.SpecFlow.MicrosoftDependencyInjection_specflow_3_7/compare/Specflow_v3_6_23...main)

I've not to real need to upgrade past 3.6.23, but I thought I'd draw your attention to it.

Thanks,
Clive

**Comment by AdCodicem** [comment]
Hi Clive, 
Thank you, I'm happy to see it's useful!
I'll check this issue soon :)
Clément

**Comment by AdCodicem** [comment]
Should be fixed with PR #4 
It will be released soon

**Comment by AdCodicem** [comment]
V 1.1.3 Released : https://www.nuget.org/packages/AdCodicem.SpecFlow.MicrosoftDependencyInjection/1.1.3

**Comment by cliveontoast** [comment]
Worked a treat. Thanks
